---
- name: 'Deprecated ⚠'
  ansible.builtin.debug:
    msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │                  Overseer support is deprecated.                  │
      │                                                                   │
      │                 Migrate to r_pufky.srv.jellyseerr                 │
      │                                                                   │
      │               Will be removed in Debian 13 (Trixie)               │
      │                                                                   │
      ╰───────────────────────────────────────────────────────────────────╯

- name: 'Prep'
  ansible.builtin.include_tasks: 'prep.yml'
- name: 'Install'
  ansible.builtin.include_tasks: 'install.yml'

- name: 'Build'
  when: not overseerr_service_force_config_only_enable
  ansible.builtin.include_tasks: 'build.yml'

- name: 'Config'
  ansible.builtin.include_tasks: 'config.yml'
